
BOARD_SIZE = 8



PLAYER_1 = "Player1"
PLAYER_2 = "Player2"



MALE_PIECE = "male"
FEMALE_PIECE = "female"
ELEMENT_PIECE = "element"



EARTH = "earth"
WATER = "water"
FIRE = "fire"
AIR = "air"

ELEMENTS = [EARTH, WATER, FIRE, AIR]



NEUTRAL_TILE = "neutral"
EARTH_TILE = "tile_earth"
WATER_TILE = "tile_water"
FIRE_TILE = "tile_fire"
AIR_TILE = "tile_air"

TILE_TYPES = [
    NEUTRAL_TILE,
    EARTH_TILE,
    WATER_TILE,
    FIRE_TILE,
    AIR_TILE,
]



PLAYER_1_MALE_SYMBOL    = "M"
PLAYER_1_FEMALE_SYMBOL  = "F"

PLAYER_1_EARTH_SYMBOL   = "Ea"
PLAYER_1_WATER_SYMBOL   = "Wa"
PLAYER_1_FIRE_SYMBOL    = "Fi"
PLAYER_1_AIR_SYMBOL     = "Ai"

PLAYER_2_MALE_SYMBOL    = "m"
PLAYER_2_FEMALE_SYMBOL  = "f"

PLAYER_2_EARTH_SYMBOL   = "ea"
PLAYER_2_WATER_SYMBOL   = "wa"
PLAYER_2_FIRE_SYMBOL    = "fi"
PLAYER_2_AIR_SYMBOL     = "ai"


PLAYER_1_ELEMENT_SYMBOL = "E"
PLAYER_2_ELEMENT_SYMBOL = "e"



WIN_REWARD = 10
NORMAL_MOVE_REWARD = 0
ILLEGAL_MOVE_PENALTY = -5



PROTOTYPE_BOARD_SIZE = 4
FULL_GAME_BOARD_SIZE = 8
PROTOTYPE_MAX_STEPS = 80
FULL_GAME_MAX_STEPS = 150